package com.blindtigergames.werescrewed.entity;

public enum EntityType {
	PLATFORM, HAZARD, SCREW, CHECKPOINT, STEAM, PLAYER, EVENTTRIGGER, SKELETON, ROOTSKELETON, ENTITY, PARTICLE_EMITTER, POWERSWITCH
}
